# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96766c36aaf1df3e38650338ecd832e819a4371077c9f6356c3c82e1c75fb20075448d80a0f97626ced6a3142aaa4f0276b08a5c34010f9fa79a6476dd3cef0c

test:
  secret_key_base: 424c5b9dae971eb88a4a3f281f7e4f99524127eadc301f0a69fc572410b8e2e6fc6665d82b1f0e467c2df601d9b3b26b0d99cd582eb286440462c02a52d3475e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
